import NavBar from "@/components/Navbar/navBar";
import ErrorJavaScript from "@/components/fallbackComponent/fallBackComponent";
import { AccountProvider } from "@/context/accountContext";
import ErrorBoundary from "@/pages/errorBoundary";
import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
//aqui se importa los estilos glabales.

export default function App({ Component, pageProps }: AppProps) {
  return (
    <ErrorBoundary fallBackComponent={<ErrorJavaScript />}>
      <Head>
        <title>Prueba tecnica</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Orbitron&family=Pragati+Narrow&family=Roboto:wght@300&display=swap"
          rel="stylesheet"
        />
      </Head>
      <AccountProvider>
        <NavBar />
        <Component {...pageProps} />
      </AccountProvider>
    </ErrorBoundary>
  );
}
